---
title: "R Notebook"
output: 
  html_document: 
    theme: paper
    toc: yes
---
# pre analyis setup
```{r include=FALSE}
library(readxl)
require(ggplot2)
require(GGally)
require(CCA)
library(CCP)
```

## data loading
```{r include=FALSE}


dataraw <- read_excel("pulppaper.xlsx")

attach(dataraw)
#data frame
data.s<-scale(dataraw, center=TRUE, scale = TRUE)
dataf <- as.data.frame(data.s)
datafr <- as.data.frame(dataraw)



X <- data.s[,2:5]
Y <- data.s[,6:9]

#unstanderdised
Xr <- datafr[,2:5]
Yr <- datafr[,6:9]

```

# correlation

```{r correlation between the variables} 
matcor(X,Y)
```


##visuals of correlations 
```{r}
corrgram::corrgram(data.s)


ggpairs(datafr, columns = c(2,6))

ggpairs(dataf)

ggpairs(datafr[,2:9])

```
y3 is fine fiber fraction

## visuals per pair of variables
```{r corrolation of the two variables groups}

x.dat <- as.data.frame(X)
y.dat <- as.data.frame(Y)

ggpairs(x.dat)
ggpairs(y.dat)

```

# Cannon method
package used cca
```{r}
canon<-cc(X,Y)

canon.nots<-cc(Xr,Yr)


canoncor<-canon$cor

```




## cancor visuals. 

```{r eval=FALSE, include=FALSE}
barplot(canoncor, main = "Canonical correlations" , col = "gray")
```

```{r}
plt.cc(canon.nots, type = "v", d1=1, d2=1,var.label = TRUE, ind.names = data.s[,1])
plt.cc(canon.nots, type = "v", d1=2, d2=2,var.label = TRUE, ind.names = data.s[,1])
```
not sure how to interpret these variables. 

## cancor corrolation table
```{r}
library(pander)
pander(canon$xcoef)
pander(canon$ycoef)

#this is the table we want
canon$scores$corr.X.yscores
canon$scores$corr.Y.xscores
```



